### ISSUE TITLE
Crashes on startup! 

### ISSUE THREAD

**Issue by KlaraChaos** [Codecrafter14/ultimatebackportmod#4]
**Describe the bug**

**To Reproduce**
1.update to newes version
2. start game
3. minecraft crahses at the last stage (using 1.12.2 pack perfectly complex)
4. see error (log says its ultimate backport and ido

**Expected behavior**
minecraft starting and i get to the main menu

**Desktop (please complete the following information):**
 - OS: windows 10
 - Browser Crome
 - Version 100

this did not happed in the prev version of the mod i tested that and it started just normally up

here the crash report file
[crash-2022-05-21_23.51.53-client.txt](https://github.com/Codecrafter14/ultimatebackportmod/files/8748443/crash-2022-05-21_23.51.53-client.txt)
!

**Comment by Codecrafter14** [comment]
OK, in a few minutes I will release a hotfix update. I hope that it will work.
